---

- name: set registries
  copy:
    content: "{{ k3s_registries_conf | to_nice_yaml }}"
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: '0644'
  when: k3s_registries_conf is defined
  notify: restart k3s-node service

- name: delete registries file if k3s_registries_conf if empty
  file:
    path: /etc/rancher/k3s/registries.yaml
    state: absent
  when: k3s_registries_conf is undefined
  notify: restart k3s-node service
